### ISSUE TITLE
deinterlacing command (+question)

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#141]
the @privatezero tutorial last week got me thinking about deinterlacing. the only yadif flag in ffmprovisr is in the "Transcode to Prores" command.

Wondering if there should be something separate for clarity, and wondering if anyone has any exp with deinterlacing filters other than yadif (I count 4 others: bwdif, kerndeint, nnedi, w3fdif).

Alternatively, does anyone have a method for controlled deinterlacing (or denoising) testing? 

thanks.

**Comment by kieranjol** [comment]
+1 for separating the yadif command from the prores recipe (if that's what
you meant)

**Comment by ablwr** [comment]
you are great / no idea

**Comment by privatezero** [comment]
Hey! Not sure if this is what you were thinking, but when I was looking into detelecine filters I used qctools to compare/analyze results. I would set it to show me the full image on one side and the field split on the other and then advance frame by frame to see what effect the filter was having. Seems like this approach could work to compare the effects of deinterlace filters!

**Comment by retokromer** [comment]
I did some quick tests in the past, I guess five years ago or so. And this should indeed be analysed again and in-depth!

At that time, the default bilinear was clearly the fastest and yadif having the best ratio between speed and quality. We have used internally a self-made filter for one single project, because the artist was unhappy with all the existing filters. It gave an excellent quality, but it was much slower than yadif. We currently use almost always yadif.

A little similar question also rises about the variants of 4:2:0 subsampling.

**Comment by kfrn** [comment]
Related, I had been thinking about an IVTC filter. Many use AVISynth for IVTC, but I'm experimenting with ffmpeg for this.  
Although, this is more for DVD-ripping than a likely archival use case.

**Comment by retokromer** [comment]
This is – at least partially – resolved by https://github.com/amiaopensource/ffmprovisr/pull/151.

**Comment by retokromer** [comment]
Some additional work on https://github.com/amiaopensource/ffmprovisr/pull/151 will be done during the next days, but I guess we are almost done. Therefore I close this one.
