### ISSUE TITLE
More scripts!

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#15]
We need MOORRRRRRREEEEE!!!

**Comment by retokromer** [comment]
My students are conceiving some potential additional scripts this week.

**Comment by kieranjol** [comment]
I have a simple 24fps to 25fps converter that performs audio pitch compensation for the 4% speedup. Handy for PAl access copies.
https://github.com/kieranjol/24to25

I'm not great at webby things so will try to figure out how to put it up this weekend when I get a chance.

**Comment by ablwr** [comment]
Pointing to this and permission is sufficient if you don't have time to convert to HTML or break down and define the flags.

**Comment by kieranjol** [comment]
That's good to know. I can always break it down at a later date. Will try to get that done by the end of the week.

**Comment by retokromer** [comment]
@kieranjol You can join both your Bash commands (image and sound) into one single ffmpeg command:
http://www.avpres.net/FFmpeg/av_speed.html

**Comment by ablwr** [comment]
Reto is a hero.

**Comment by retokromer** [comment]
No, just perverse: I love -filter_complex

**Comment by kieranjol** [comment]
<3
That is beautiful! Thanks Reto!!!

**Comment by retokromer** [comment]
BTW @kieranjol: I personally prefer "setpts=(24/25)*PTS" over "setpts=0.96*PTS", because if one day we should come back to the good old Gray code, then we would have less rounding errors.

If you have other commands, you are very welcome to edit, or to send me an email with the full command or just the idea of a command. Any input from the field is most welcome!

**Comment by kieranjol** [comment]
Hi Reto,

Thanks for that on all fronts. I need to alter my original script to your
one liner when I get the chance.

Cheers,

Kieran.

**Comment by dericed** [comment]
ratios rule! Numerator and denominator or GTFO!

**Comment by retokromer** [comment]
@dericed Added the ratio rules. I hope my English is not too bad...

**Comment by kieranjol** [comment]
I think this might be the best place for a note to self, inspired by https://github.com/amiaopensource/ffmprovisr/issues/42:
These are mostly access related, but perhaps aspect ratio/sar/dar correction could be useful in a archival context, depending on the context.
1. How to change aspect ratio with `-aspect` or `-setsar/setdar`
2. How to hange field order with `-setfield`
3. How to desaturate for access copies (I don't actually know how to do this yet with ffmpeg but we have some telecined B&W tapes that have crazy excessive chroma values due to wonky transfers.)
4. Burn in subtitles (A colleague had to do this recently when exhibiting a file with external subs. They were dvdsubs, not text based, so we uses the overlay filter.http://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo

**Comment by retokromer** [comment]
:+1:
Perhaps in AMIA Hackday 2016 we should try to integrate all of them: FFmpeg, QCTools, MediaInfo/Conch and LTO control scripts.

**Comment by retokromer** [comment]
Do we still need this open issue, @ablwr and @kieranjol? We have added plenty of scripts since the 2015–12–02!

**Comment by ablwr** [comment]
Always more!!!!!! But maybe not a useful issue (since this is now stressed in the readme).

**Comment by retokromer** [comment]
In my opinion, an issue should contain a concrete idea for a command or a concrete goal to reach.

**Comment by ablwr** [comment]
Agreed!
