### ISSUE TITLE
input > process > output

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#17]
What about a little different structure?
One can chose between
- different input formats, 
- different actions to apply, and 
- different output formats.

Then the app generates the corresponding window with the full command and the related explanations.
(As it's three-dimensional, that would be a kind Rubik's Cube for audio-visual archivists.)

**Comment by ablwr** [comment]
This might have been how the app was originally set up -- it was more like a guided form where you'd click on what you'd like to do, be prompted for input and output, and it would generate the script. But I felt it was a little too hand-holdy because anyone capable of brew install ffmpeg successfully is probably more than capable at figuring out how to manipulate scripts. But do you mean something else?

**Comment by retokromer** [comment]
I was thinking e.g. about:
- A folder with 2K DPX files
- has to be filtered as HD (aka down-scaled and pillarboxed) into
- ProRes Proxy.

The scaling and padding filters are exactly the same as if I up-scale "uncompressed" "YUV" 640 x 480 into HD MP4/H.264.

**Comment by ablwr** [comment]
ffmprovisr 2.0. This makes sense for some commands but not others. Do you think a hybrid approach is possible?

**Comment by retokromer** [comment]
Of course! It makes sense for filtering, not for transcoding.

**Comment by retokromer** [comment]
Perhaps https://github.com/amiaopensource/ffmprovisr/issues/2 can be merged with this «issue»?

**Comment by ablwr** [comment]
Closing as a way to merge with #2
