### ISSUE TITLE
wav to flac command

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#279]
hey,
wondering if someone could help me put together a solid broadcast wav to flac command. there are a lot of options that mean nothing to me (Cholesky factorization passes?), and others that I'm more generally curious about (on a compression level scale of 0-12, ffmpeg defaults to 5, but I've read that 2 should be considered "your friend"). 

also wondering if anyone has a strong opinion about using the flac utility instead of ffmpeg.

thanks all!

**Comment by retokromer** [comment]
There is also the [`flake`](http://flake-enc.sourceforge.net) encoder, but I don’t know if this is still maintained. (We used `flac`.)

**Comment by privatezero** [comment]
+1 for using `flac`! I use a slightly tweaked (not deleting the input) version of the command that @dericed put together for his post about [FLAC in the Archives](http://dericed.com/2013/flac-in-the-archives/)

`flac --best --keep-foreign-metadata --preserve-modtime --verify input.wav`

Since what makes a Broadcast WAV a Broadcast WAV is just the inclusion of the extra metadata, I liked how the `--keep-foreign-metadata` tag would store that metadata and make the process truly reversible! (Even though it screams about being experimental). Not sure if FFmpeg's FLAC encoder has that option.

Also, ran into some weird issues where just a few 24 bit mono files transcoded to FLAC via FFmpeg were failing validation via the official `flac` tool, but I was communicating with the engineer who was having problems remotely at the time and wasn't able to dive into figuring out what was going on.

**Comment by privatezero** [comment]
Oh, as a follow up, `flac` is in homebrew, so a usual `brew install flac` will get you where you need to be to experiment! 

This will also get you `metaflac` which opens up tagging and embedding data (such as an image of the item) within the flac itself, so might be worth looking into what else FLAC would let you do besides just preserving the BWF info!

**Comment by privatezero** [comment]
Here is an example command for some metadata embedding (I am using this for a personal archiving project). 

`metaflac --set-tag=SOURCEMEDIA="A=ANALOGUE,M=stereo,T=Sony TC-D5 PROII; 1 7/8 ips; Compact Cassette" --set-tag=LOCATION="+40.81013-073.94758" --set-tag=DATE="2017-03-18 (recorded)" --set-tag=LICENSE="CC BY 4.0 Attribution : Andrew Weaver" --import-picture-from="13||||/input.jpg" input.flac`

Sorry to gush about FLAC!! But it is good!!

**Comment by bturkus** [comment]
thanks for all the info. I was playing around with the flac utility earlier today, and even when using the --keep-foreign-metadata flag, it didn't seem to be retaining the extra metadata from my broadcast wav. sorry for the screenshotz, but:

Exhibit A:
![screen shot 2017-11-15 at 5 51 53 pm](https://user-images.githubusercontent.com/8987230/32864593-ccaece84-ca2d-11e7-94c2-881f4bcce081.png)

Exhibit B:
![screen shot 2017-11-15 at 5 52 12 pm](https://user-images.githubusercontent.com/8987230/32864617-ddd5755a-ca2d-11e7-9915-dccd38ef8946.png)

when using ffmpeg, I didn't have the same prob. thoughts?

**Comment by privatezero** [comment]
You should be able to see the BWF metadata if you reverse the process (.flac back to a .wav) with `flac --decode --keep-foreign-metadata --preserve-modtime --verify input.flac`.

The data is all in there and the BWF can be perfectly recreated, mediainfo is only showing the flac metadata and not the embedded foreign metadata. When you were using FFmpeg, I suspect it might have been auto-converting some of the BWF metadata to tags (like it does when you go BWF -> mp3) which is why they showed up, but that is different from actually storing the BWF metadata via `--keep-foreign-metadata.`

Take a close look at the tag names for the BWF and the FFmpeg created FLAC -  On my end, crunching a BWF to a flac using FFmpeg does things like change the `Archival Location` tag to `encoded_by` etc.

**Comment by kfrn** [comment]
Hey, I don't have any info to add, but this is a great thread. Thanks!

**Comment by retokromer** [comment]
Indeed, we – and our clients as well – use `flac` with `brew`. It works just wonderful.

**Comment by richardpl** [comment]
Use ffmpeg's flac if you want to do special encoding with smallest files.

**Comment by dericed** [comment]
ffmpeg's flac does not offer --keep-foreign-metadata (from flac utility), so some container data from input (iXML, aXML, cart, cues, lvl, etc) may be lost

**Comment by todrobbins** [comment]
THIS THREAD:

![giphy](https://user-images.githubusercontent.com/158590/37976811-8f5f8030-319f-11e8-821a-16981551f5f5.gif)

PS: are there any good GUIs for `flac`/`metaflac`?

**Comment by privatezero** [comment]
Additionally ffmpg's flac seems to create files that do not pass flac validation from time to time when dealing with 24 bit mono

**Comment by richardpl** [comment]
@privatezero have you reported such issue to trac?

**Comment by privatezero** [comment]
@richardpl this is something I need to follow up on - the offending files were created at a different institution and their engineer said he would report it to trac, however I don't think that he did.

As I do not have access to their files anymore, I haven't created an issue myself. I will try reaching out to them again.

**Comment by richardpl** [comment]
@todrobbins we are programmers, GUIs are for kids.

**Comment by ablwr** [comment]
Not everyone is a programmer and GUIs are useful for people that do not have that particular skillset. Please avoid the use of [insulting/derogatory comments](https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/code_of_conduct.md)!

**Comment by kieranjol** [comment]
I'm guilty here as well with my heart emoji (which I removed) , I wasn't really thinking - sorry Tod, and +1 @ablwr.

**Comment by kfrn** [comment]
> richardpl commented 3 hours ago
> @todrobbins we are programmers, GUIs are for kids.

Bro ....

**Comment by privatezero** [comment]
@richardpl regarding issues with the flac tool throwing errors with certain 24 bit mono files that were processed by ffmpeg - I reached out to the institution holding the files and am unable to recreate the problem as previously reported using the supplied test files.

It would seem that this is no longer a concern.

**Comment by privatezero** [comment]
Resolved in https://github.com/amiaopensource/ffmprovisr/pull/338
