### ISSUE TITLE
New recipe: Create a mosaic out of several input videos

### ISSUE THREAD

**Issue by todrobbins** [amiaopensource/ffmprovisr#348]
Would anyone want me to reformat and credit this recipe?

![image](https://user-images.githubusercontent.com/158590/46507602-92963580-c7f6-11e8-82fb-acfebfa9825b.png)

https://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos

**Comment by kfrn** [comment]
Looks cool! I say go for it :)

**Comment by richardpl** [comment]
That is old way, you really should use vstack, hstack filters instead of slow overlay.

**Comment by bturkus** [comment]
ah that's a good point. maybe this from audiorecorder could help? I find it to be a fairly clear example of hstack/vstack.

`FILTER_CHAIN="asplit=6[out1][a][b][c][d][e],\
[e]showvolume=w=700:c=0xff0000:r=30[e1],\
[a]showfreqs=mode=bar:cmode=separate:size=300x300:colors=magenta|yellow[a1],\
[a1]drawbox=12:0:3:300:white@0.2[a2],[a2]drawbox=66:0:3:300:white@0.2[a3],[a3]drawbox=135:0:3:300:white@0.2[a4],[a4]drawbox=202:0:3:300:white@0.2[a5],[a5]drawbox=271:0:3:300:white@0.2[aa],\
[b]avectorscope=s=300x300:r=30:zoom=5[b1],\
[b1]drawgrid=x=150:y=150:c=white@0.3[bb],\
[c]showspectrum=s=400x600:slide=scroll:mode=combined:color=rainbow:scale=lin:saturation=4[cc],\
[d]astats=metadata=1:reset=1,adrawgraph=lavfi.astats.Overall.Peak_level:max=0:min=-30.0:size=700x256:bg=Black[dd],\
[dd]drawbox=0:0:700:42:hotpink@0.2:t=42[ddd],\
[aa][bb]vstack[aabb],[aabb][cc]hstack[aabbcc],[aabbcc][ddd]vstack[aabbccdd],[e1][aabbccdd]vstack[z],\
[z]drawtext=fontfile="${FONTPATH}": text='%{pts \\: hms}':x=460: y=50:fontcolor=white:fontsize=30:box=1:boxcolor=0x00000000@1[fps],[fps]fps=fps=30[out0]"`

**Comment by privatezero** [comment]
@todrobbins could be cool do do a recipe on the new [xstack](https://ffmpeg.org/ffmpeg-filters.html#xstack) filter too!

**Comment by todrobbins** [comment]
Honestly, I don't understand these commands that well so maybe @richardpl or @bturkus should write it up. 🤣

**Comment by privatezero** [comment]
No worries @todrobbins! Thanks for drawing attention that we could use a recipe of this nature!

**Comment by bturkus** [comment]
is [xstack](https://ffmpeg.org/ffmpeg-filters.html#xstack) the new hotness?

**Comment by dericed** [comment]
@bturkus you know it. Check out https://github.com/amiaopensource/vrecord/commit/4e3f45b7f0804296daf1da928bf8b803087d9ff9. 
xstack has me and four of my friends all like `0_0 | 0_h0 | 0_h0+h1 | w0_0 | w0_h0`

**Comment by richardpl** [comment]
Using xstack, over combinations of various hstack/vstack should be much faster.
So only cases when hstack/vstack may be useful is when one does not need complex stacking, but just horizontal or vertical stacking of several videos.

You can use fixed numbers in xstack to set exact spot in frame one of inputs will appear:

So for examples: take 4 videos each size of 400x300:
2x2 xstack incarnation would be: xstack=inputs=4:layout=0_0|0_300|400_0|400_300
or variant when you do not need to know sizes, but you know all sizes are same:
xstack=inputs=4:layout=0_0|0_h0|w0_0|w0_h0
Note that you can change order of these but must make sure that Xth input is not referencing itself, as that is invalid, illogical and not accepted.
so this one is invalid: xstack=inputs=4:layout=0_0|0_h1|w0_0|w0_h0
It is invalid because 2nd input ( 0_h1 ) is referencing itself (h1).
It is also invalid to use numbers for referencing that are >= of number of inputs. Counting always start from 0 here.

**Comment by retokromer** [comment]
+1

**Comment by ghost** [comment]
You can copy and paste and/or modify/adapt any of the content from my answer (or any other of my answers you find on SE).
[Vertically or horizontally stack several videos using ffmpeg?](https://stackoverflow.com/a/33764934/1109017)

**Comment by kieranjol** [comment]
Oh my god you're lordneckbeard? I've always wondered who that was.

**Comment by ablwr** [comment]
Holy shit @llogan, you're a legand

**Comment by ghost** [comment]
> Oh my god you're lordneckbeard? I've always wondered who that was.

I should have chose a less idiotic username...

> Holy shit @llogan, you're a legand

Thanks, but I don't know about that. Mostly just procrastinating at work and home.

**Comment by ablwr** [comment]
Resolved in #362? I leave it up to @todrobbins to decide!

**Comment by todrobbins** [comment]
![youbetcha](https://user-images.githubusercontent.com/158590/50713482-67f48c80-1032-11e9-98e5-43607c182917.gif)
