### ISSUE TITLE
Color vs colour

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#357]
:grimacing: 

We use two styles of English on ffmprovisr and I think we should get consistent and use one or the other. Due to the ratio of former-and-present maintainers, it would seem "colour" would win out. But on the other hand, the official documentation uses "color." I believe this was set in the standard for Matroska as well (right, @retokromer?), so it may be more of the industry standard to use an American styling.

What do you think?

**Comment by kieranjol** [comment]
As a "colour" user, I'm totally fine with keeping it American for the
reasons you've outlined.

**Comment by retokromer** [comment]
@ablwr Yes, this rule was adopted in the Matroska specifications: https://github.com/Matroska-Org/matroska-specification/pull/292

**Comment by privatezero** [comment]
I'm a little bit against enforcing a specific style of English! (And not just because I am a frequent accidental traitor to Webster's English). I think due to the nature of the project, being literally intercontinental, it is more representative of contributors as well as creates less barriers to potential new contributors to not have this type of style requirement.

Additionally, it opens a can of worms for the many many subtle differences in style. In the context of the project, is there any actual benefit to standardizing to a particular form of English?

**Comment by ablwr** [comment]
I think it's worth using the same style as the official documentation, maybe people are doing a ctrl-f for "color" or "colour" and receiving partial results?

**Comment by privatezero** [comment]
Hmm, that is a good point about partial results...but in the case of a hypothetical ctrl-f search error I am not sure if partial results is better or worse than zero results caused by searching the alternate spelling.

Just in general, as a project that arose in a sense due to the shortcomings of the official FFmpeg documentation, and that is expanding to include other resources, I don't think we necessarily need to be bound to their style guide as the ultimate authority outside of the actual script syntax.

I dunno, just not sure how I feel about giving official primacy to a certain strain of English in an international project, particularly one that has heavy contributions and presumably use from outside the sphere of US English.

That being said, if the rest of y'all agree that is the way to go, I won't stand against it!

**Comment by ablwr** [comment]
This was auto-closed by @retokromer's PR being merged, but I am happy to keep this open and continue the discussion. I don't have strong feelings either way.

**Comment by retokromer** [comment]
If my PR is reverted, then please fix the error which I fixed _en passant_: `trandscodes` > `transcodes`. Thank you!

**Comment by kfrn** [comment]
I use Commonwealth spelling obviously, but probably some Americanisms creep in. Not strong feelings either way. (Even if I do think that "color" looks so naked without the 'u', lol!)
